run_name: DidiCond_real

dataset_params:
  type: Omnifold
  path: /Users/huetsch/Desktop/data/Omnifold.npz
  path2: /remote/gpu07/huetsch/data/omnifold_data/Omnifold.npz
  n_data: 500000

model_params:
  type: Didi
  hidden_layers: 4
  internal_size: 64
  lr: 1.e-3
  n_epochs: 100
  batch_size: 1024
  batch_size_sample: 8192

  cond_x1: True
  noise_scale: 1.e-1
  n_steps: 1000
