run_name: Didi_20m_Big_100e_Shifted

dataset_params:
  type: Omnifold
  path: /Users/huetsch/Desktop/data/Omnifold.npz
  path_train: /remote/gpu07/huetsch/data/omnifold_data/OmniFold_big/OmniFold_train_large.h5 #/remote/gpu07/huetsch/data/omnifold_data/Omnifold.npz
  n_train: 20000000
  path_test: /remote/gpu07/huetsch/data/omnifold_data/OmniFold_big/OmniFold_test.h5 #/remote/gpu07/huetsch/data/omnifold_data/Omnifold.npz
  n_test: 4000000
  shift_gen: True

model_params:
  type: Didi
  hidden_layers: 8
  internal_size: 512
  lr: 1.e-3
  n_epochs: 100
  batch_size: 16384
  batch_size_sample: 16384

  cond_x1: False
  noise_scale: 0.1
  n_steps: 1000
